### ISSUE TITLE
Millstone only works the first time

### ISSUE THREAD

**Issue by PineJamX** [W1nter-isHere/PrimitiveUtilities#1]
https://user-images.githubusercontent.com/101681286/158496820-bdc1c87c-68da-4b22-a81f-16f615b9ada1.mp4

Millstone can place multiple items. But, millstone only processes one item when place multiple items. In this case, I think the millstone needs to be processed continuously.
This is the CraftTweaker script used in the video.
`<recipetype:primutils:milling>.addJSONRecipe("pj_milling_plant2flour", {
    "input": {
        "tag": "forge:flour_plants"
    },
    "total_progress": 2,
    "output": [
        {
            "result": {
                "item": "pamhc2foodcore:flouritem"
            },
            "chance": 100
        }
    ]
});`
(I'm not English speaker, so it may be an unnatural sentence.)

**Comment by winterSteve25** [comment]
Thanks for reporting, I'll take a look. :)

**Comment by winterSteve25** [comment]
Ok, I think this should fix it, can you try it out before I publish the changes? https://github.com/W1nter-isHere/PrimitiveUtilities/releases/tag/Beta

**Comment by PineJamX** [comment]
It works perfectly!
Thank you for your support!

**Comment by winterSteve25** [comment]
No problem, glad it works. The changes will be published.
