### ISSUE TITLE
Crash with Primitive Utilities mod

### ISSUE THREAD

**Issue by Hideki2D** [W1nter-isHere/PrimitiveUtilities#2]
Hello, i have crash with millstone
[crash-2022-03-23_14.49.59-server.txt](https://github.com/W1nter-isHere/PrimitiveUtilities/files/8333093/crash-2022-03-23_14.49.59-server.txt)
I tried add recipes with kubjs, crafttweaker and with datapack, but all of this crashed game
I used recipe from example
I tried to use different versions of geckolib, fclib, forge. but this didnt work
can you help me with solving this problem?

**Comment by winterSteve25** [comment]
Yep, expect an update within hours.

**Comment by winterSteve25** [comment]
Ok I made a beta version, see if this fixes it. https://github.com/W1nter-isHere/PrimitiveUtilities/releases/tag/BetaV1.0.2

**Comment by Hideki2D** [comment]
its work for me, thanks
