### ISSUE TITLE
The Drying Rack of doom

### ISSUE THREAD

**Issue by SheReyy** [W1nter-isHere/PrimitiveUtilities#4]
Forge: 36.2.33
Primus Utils: primutils-1.0.2.jar

Hi! I wanted to report a bug related to the drying rack. Sometimes it will.. just break (not actually break), and it will delete some of its contents. After that, if you try to place a tool in it, that tool will be deleted. I don't really have a log file for this issue, but I might get my hands on one, if it's needed. Also, this issue is kinda rare, but I'd be more interested in fixing the whole "any tool placed in it will be deleted" part, since you can accidentally place a good tool in there and loose it forever.

Edit: Update un this. So here are some steps to reproduce this:
1. Place an item on Drying Rack via right click
2. Wait until that items gets turned into something else
3. Without removing the result of the recipe, place another item via right click.
4. That item disappears!

Seems like it's not just tools, but any item.

**Comment by winterSteve25** [comment]
Thanks for reporting this issue. I will take a look.

**Comment by winterSteve25** [comment]
https://github.com/W1nter-isHere/PrimitiveUtilities/releases/tag/BetaV1.0.3 alright can you try this? This should fix the problem

**Comment by SheReyy** [comment]
> https://github.com/W1nter-isHere/PrimitiveUtilities/releases/tag/BetaV1.0.3 alright can you try this? This should fix the problem

Sorry for the long response time. I'd check this out, but I've got another issue with the chopping block. I'll post it shortly.

**Comment by SheReyy** [comment]
> https://github.com/W1nter-isHere/PrimitiveUtilities/releases/tag/BetaV1.0.3 alright can you try this? This should fix the problem

Also, yeah. Seems like the drying rack is fixed, at least on singelplayer. Can't really test it on multiplayer, but I'll assume it works just fine.
