### ISSUE TITLE
Chopping Block Enhancement

### ISSUE THREAD

**Issue by SheReyy** [W1nter-isHere/PrimitiveUtilities#5]
I was wondering if it could be possible to make so that, you can't place items on the Chopping Block, from you off hand, similar to how the Cutting Board from Farmer's Delight works. It kinda gets frustrating to chop some logs, and then, end up with your axe on the Block itself.

**Comment by winterSteve25** [comment]
Thank you for your suggestion, I will take a look at it.

**Comment by winterSteve25** [comment]
Added config to only accept main hand items
