### ISSUE TITLE
Chopping Block crash on server

### ISSUE THREAD

**Issue by SheReyy** [W1nter-isHere/PrimitiveUtilities#6]
Ok, I'll be honest at this point. I'm not the one who discovers these bugs. I'm the owner of a pack and I'm using your mod in it. The issues mentioned until this point, were discovered by my players. Now, one of my players told me that, on a server, if you break the chopping block, you and the nearby players, get a crash.

[Here](https://gist.github.com/IamRyan30/42fa6c6f7ea1a3113b1ff6cadada62be)'s the crash error.

If it is required, I can ask them for the whole log related to the problem and I can leave it here.

**Comment by SheReyy** [comment]
Update on this. Apparently the drying rack is also.. related to this..? Somehow. The whole issue is related to optifine, as shown by the crash log, so I'm not sure if it's worth trying to solve it. The thing is, only these stations are causing crashes with optifine. Other blocks, from other mods, work.. ok.

**Comment by SheReyy** [comment]
Another update. So the drying rack crash is the exact same as the one caused by the chopping block. The players who reported these issues were using optifine with shaders. I think the issue is related just with the shaders in general.

**Comment by winterSteve25** [comment]
I am not too sure why this is happening exactly, but I can add a few lines just to prevent it from crashing.

**Comment by winterSteve25** [comment]
Also if the chopping block has the issue I expect other blocks to have the same issue since they are rendered the same way.

**Comment by SheReyy** [comment]
> I am not too sure why this is happening exactly, but I can add a few lines just to prevent it from crashing.

If that helps in any way, it would be perfect. So far, it looks like the mod works fine just with optifine. It's the shaders that are breaking the game, so I'm going to tell my players to not use them. Kinda sad news, since they like playing with shaders, but I'd rather have some ugly stability, then a beautiful mess.

**Comment by winterSteve25** [comment]
Alright I'll get an update out as soon as I can, after that they should be able to use shaders. Sorry for the inconvenience

**Comment by SheReyy** [comment]
No problem. Thanks a lot for working on this issue.
