### ISSUE TITLE
Crash when breaking chopping block

### ISSUE THREAD

**Issue by Quarris** [W1nter-isHere/PrimitiveUtilities#8]
Hey I got a [crash](https://gist.github.com/Quarris/08a8fd0b78dbdde7cf89b2e83e5a2dd7) when breaking the chopping block.
I suspect it might be with matrix push/pop being out of sync when you return [here](https://github.com/W1nter-isHere/PrimitiveUtilities/blob/f359f155ccc7817ba7f55177a627c0f6bc93f9d5/src/main/java/wintersteve25/primutils/client/ChoppingBlockTESR.java#L30); might fix to move the push right before the `setupMatrix()` method call.

Mc: 1.16.5
Forge: 36.2.34
Mod: primutils-1.0.3.jar

**Comment by Quarris** [comment]
If I tested out the issue could I make a PR with the fix for upload? We really would like to use this but can't :/

**Comment by winterSteve25** [comment]
Hey, sorry for the inconvenience. Yes you can absolutely make a PR if you have a fix, but if not I'm happy to fix it myself. :)

Thanks for reporting

**Comment by winterSteve25** [comment]
I think your suspicion is probably correct, and in that case the problem exist in the other blocks as well
